name: dujis_partner
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animation_wrappers: ^3.0.0
  cached_network_image: ^3.2.3
  country_code_picker: ^3.0.0
  charts_painter: ^3.1.1
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.12.0
  flutter_phoenix: ^1.1.0
  flutter_bloc: ^8.1.2
  flutter_polyline_points: ^1.0.0
  flutter_native_splash: ^2.2.18
  freezed_annotation: ^2.1.0
  google_maps_flutter: ^2.2.5
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  logger: ^1.3.0
  material_dialogs: ^1.1.4
  onesignal_flutter: ^3.5.1
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.0.13
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.0.20
  # intl: ^0.18.0
  url_launcher: ^6.1.12
  device_info_plus: ^9.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  device_preview: ^1.1.0
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/logo/app_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/app_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/file/
    - assets/icons/
    - assets/images/account/
    - assets/images/address/
    - assets/images/custom/
    - assets/images/footmenu/
    - assets/images/logo/
    - assets/images/other/
    - assets/images/seller/
    - assets/images/veg/
