class Languages {
  Map<String, String> english() {
    return {
      'lightMode': 'Light Mode',
      'lightText': 'Experience an exciting light mode',
      'accepted': 'Accepted',
      'submit': 'Submit',
      'outStock': 'Out of Stock',
      'setLocation': 'Set delivery location',
      'enterLocation': 'Enter location',
      'review': 'My Reviews',
      'hey':
          'Hey Samantha,\n\nYou’re almost in. \nProvide your phone number \nfor verification.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'Awesome food taste as well as quick delivery service.  Really appreciate the packing and quality of food delivered. Go for it !!',
      'content2':
          'Quick delivery service & Really good  taste of food.  Really appreciate the packing and quality of food delivered. Must order Chicken Curry.',
      'language': 'Select Language',
      'display': 'Select Mode',
      'darkMode': 'Dark Mode',
      'darkText': 'Experience an exciting dark mode',
      'settings': 'Settings',
      'or': 'Or',
      'continueWith': 'Continue With ',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'Apple',
      'invalidNumber': 'Invalid Number',
      'networkError': 'Network Error',
      'bodyText1': 'Delivering almost',
      'bodyText2': 'Everything.',
      'mobileText': 'Enter mobile number',
      'continueText': 'Continue',
      'register': 'Register',
      'invalidName': 'Invalid Name',
      'invalidEmail': 'Invalid Email',
      'invalidNameAndEmail': 'Invalid Name and Email',
      'fullName': 'Store Name',
      'emailAddress': 'Email Address',
      'mobileNumber': 'Mobile Number',
      'verificationText':
          'We\'ll send verification code on above given number.',
      'verification': 'Verification',
      'checkNetwork': 'Check your network or phone number entered',
      'invalidOTP': 'Invalid OTP',
      'enterVerification':
          'Enter verification code we\'ve sent on given number.',
      'verificationCode': 'ENTER VERIFICATION CODE',
      'resend': 'Resend',
      'offlineText': 'You\'re Offline',
      'onlineText': 'You\'re Online',
      'goOnline': 'GO ONLINE',
      'goOffline': 'GO OFFLINE',
      'orders': 'Orders',
      'newOrder': 'NEW ORDERS',
      'pastOrder': 'PAST ORDERS',
      'itemSold': 'Items Sold',
      'items': 'Items',
      'earnings': 'Earnings',
      'location': 'Location permission denied!\nGrant the location to the app.',
      'grant': 'Grant',
      'homeText': 'Home',
      'account': 'My Account',
      'orderText': 'My Orders',
      'insight': 'Insight',
      'wallet': 'Wallet',
      'tnc': 'Terms & Conditions',
      'support': 'Support',
      'aboutUs': 'About Us',
      'logout': 'Logout',
      'login': 'Login',
      'loggingOut': 'Logging Out',
      'areYouSure': 'Are you sure?',
      'yes': 'Yes',
      'no': 'No',
      'heyThere': 'Hey there?\nHow much time?',
      'onMyWay': 'On my way ma\'am.\nWill reach in 10 mins',
      'sendToBank': 'Send to Bank',
      'availableBalance': 'Available Balance',
      'bankInfo': 'Bank Info',
      'accountHolderName': 'Account Holder Name',
      'bankName': 'Bank Name',
      'branchCode': 'Branch Code',
      'accountNumber': 'Account Number',
      'enterAmountToTransfer': 'Enter amount to transfer',
      'aboutDelivoo': 'About Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'Our Vision',
      'companyPolicy': 'Company Policy',
      'termsOfUse': 'Terms of Use',
      'message': 'Your Message',
      'enterMessage': 'Type your message',
      'orWrite': 'Or Write us your queries',
      'yourWords': 'Your words means a lot to us.',
      'online': 'Online',
      'recent': 'Recent',
      'vegetable': 'Vegetables & Fruits',
      'today': 'TODAY',
      'viewAll': 'View all Transactions',
      'editProfile': 'Edit Profile',
      'featureImage': 'Feature Image',
      'uploadPhoto': 'Upload Photo',
      'profileInfo': 'Store Info',
      'gender': 'Gender',
      'updateInfo': 'Update Info',
      'instruction': 'Keep tomatoes in separate bag please.',
      'cod': 'Cash on Delivery',
      'viewOrderInfo': 'View Order Info',
      'store': 'Silver Leaf Vegetables',
      'ready': 'Ready to Deliver',
      'storeText': 'Union Market',
      'storeProfile': '\nStore Profile',
      'tomato': 'Fresh Red Tomatoes',
      'onion': 'Fresh Red Onions',
      'fingers': 'Fresh Lady Fingers',
      'top': 'TOP 5 SELLING ITEMS\n',
      'total': 'Total 112 item sales',
      'sales': 'Sales',
      'vegetables': 'VEGETABLES',
      'fruits': 'FRUITS',
      'herbs': 'HERBS',
      'dairy': 'DAIRY',
      'deliveryPartner': 'Delivery Partner Assigned',
      'category': 'Category',
      'address': 'Address',
      'storeAddress': 'Store Address',
      'storeTimings': 'Store Timings',
      'openingTime': 'Opening Time',
      'closingTime': 'Closing Time',
      'product': 'My Products',
      'stock': 'In Stock',
      'pending': 'Pending',
      'item': 'ITEM(S)',
      'sub': 'Sub Total',
      'service': 'Service Fee',
      'payment': 'Payment Info',
      'add': 'Add Product',
      'edit': 'Edit Product',
      'info': 'ITEM INFO',
      'title': 'ITEM TITLE',
      'enterTitle': 'Enter Item Name',
      'itemCategory': 'ITEM CATEGORY',
      'selectCategory': 'Select Item Category',
      'price': 'ITEM PRICE',
      'enterPrice': 'Enter Price',
      'quantity': 'QUANTITY',
      'orderNumber': 'Order Num',
      'enterQuantity': 'Enter Quantity',
      'addMore': '+ ADD MORE OPTIONS',
      'image': 'Item Image',
    };
  }

  Map<String, String> spanish() {
    return {
      'lightMode': 'Modo de luz',
      'lightText': 'Experimenta un emocionante modo de luz',
      'accepted': 'aceptada',
      'submit': 'Enviar',
      'outStock': 'Agotado',
      'setLocation': 'Conjunto lugar de entrega',
      'enterLocation': 'Introduzca la ubicación',
      'review': 'Mis críticas',
      'hey':
          'Hey Samantha,\n\n ya casi en. \nProporcionar su número de \nteléfono para su verificación.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'sabor de la comida impresionante, así como servicio de entrega rápida. Realmente aprecio el embalaje y la calidad de los alimentos entregados. Ve a por ello !!',
      'content2':
          'servicio de entrega rápida y realmente el buen gusto de los alimentos. Realmente aprecio el embalaje y la calidad de los alimentos entregados. Debe pedir pollo al curry.',
      'language': 'Seleccione el idioma',
      'display': 'Seleccionar modo',
      'darkMode': 'Modo oscura',
      'darkText': 'La experiencia de un modo oscuro emocionante',
      'settings': 'ajustes',
      'or': 'O',
      'continueWith': 'Continua con',
      'facebook': 'Facebook',
      'google': 'google',
      'apple': 'manzana',
      'invalidNumber': 'Número invalido',
      'networkError': 'Error de red',
      'bodyText1': 'Entregando casi',
      'bodyText2': 'Todo.',
      'mobileText': 'Ingrese el número de teléfono móvil',
      'continueText': 'Seguir',
      'register': 'Registrarse',
      'invalidName': 'Nombre inválido',
      'invalidEmail': 'Email inválido',
      'invalidNameAndEmail': 'Nombre y correo electrónico no válidos',
      'fullName': 'Nombre de la tienda',
      'emailAddress': 'Dirección de correo electrónico',
      'mobileNumber': 'Número de teléfono móvil',
      'verificationText':
          'Enviaremos el código de verificación al número dado anteriormente.',
      'verification': 'Verificación',
      'checkNetwork': 'Verifique su red o número de teléfono ingresado',
      'invalidOTP': 'OTP inválido',
      'enterVerification':
          'Ingrese el código de verificación que enviamos en un número dado.',
      'verificationCode': 'INGRESE EL CÓDIGO DE VERIFICACIÓN',
      'resend': 'Reenviar',
      'offlineText': 'Estás fuera de línea',
      'onlineText': 'Estás en línea',
      'goOnline': 'IR EN LÍNEA',
      'goOffline': 'SALIR DE LÍNEA',
      'orders': 'Pedidos',
      'itemSold': 'Cosas vendidas',
      'earnings': 'Ganancias',
      'location':
          'Permiso de ubicación denegado! \ Otorgue la ubicación a la aplicación.',
      'grant': 'Conceder',
      'homeText': 'Hogar',
      'account': 'Mi cuenta',
      'orderText': 'Mis ordenes',
      'insight': 'Visión',
      'wallet': 'Billetera',
      'tnc': 'Términos y condiciones',
      'support': 'Apoyo',
      'aboutUs': 'Sobre nosotros',
      'logout': 'Cerrar sesión',
      'login': 'Iniciar sesión',
      'loggingOut': 'Saliendo de tu cuenta',
      'areYouSure': 'Estas seguro',
      'yes': 'si',
      'no': 'No',
      'sendToBank': 'Enviar al banco',
      'availableBalance': 'Saldo disponible',
      'bankInfo': 'Información del banco',
      'accountHolderName': 'nombre del titular de la cuenta',
      'bankName': 'Nombre del banco',
      'branchCode': 'Código de sucursal',
      'accountNumber': 'Número de cuenta',
      'enterAmountToTransfer': 'Ingrese el monto a transferir',
      'aboutDelivoo': 'Sobre Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'Nuestra visión',
      'companyPolicy': 'Política de la compañía',
      'termsOfUse': 'Términos de Uso\'Términos de Uso',
      'message': 'Tu mensaje',
      'enterMessage': 'Escribe tu mensaje',
      'orWrite': 'O escríbanos sus consultas',
      'yourWords': 'Tus palabras significan mucho para nosotros.',
      'online': 'En línea',
      'recent': 'Reciente',
      'vegetable': 'Verduras y frutas',
      'today': 'HOY',
      'viewAll': 'Ver todas las transacciones',
      'editProfile': 'Ver todas las transacciones',
      'featureImage': 'Foto principal',
      'uploadPhoto': 'Subir foto',
      'profileInfo': 'Información de la tienda',
      'gender': 'Género',
      'updateInfo': 'Actualizar información',
      'instruction': 'Mantenga los tomates en una bolsa separada por favor.',
      'cod': 'Contra reembolso',
      'viewOrderInfo': 'Ver información del pedido',
      'store': 'Vegetal de hoja de plata',
      'ready': 'Listo para entregar',
      'storeText': 'Mercado de la Unión',
      'storeProfile': 'Perfil de tienda',
      'tomato': 'Tomates rojos frescos',
      'onion': 'Cebollas rojas frescas',
      'fingers': 'Fresh Lady Finger',
      'top': 'TOP 5 ARTÍCULOS DE VENTA',
      'total': 'Ventas totales de 112 artículos',
      'sales': 'Ventas',
      'category': 'Categoría',
      'address': 'Habla a',
      'storeAddress': 'Dirección de la tienda',
      'storeTimings': 'Tiempos de tienda',
      'openingTime': 'Hora de apertura',
      'closingTime': 'Hora de cierre',
      'product': 'Mis productos',
      'stock': 'En stock',
      'pending': 'Pendiente',
      'item': 'ARTICULO(S)',
      'sub': 'Subtotal',
      'service': 'Tarifa de servicio',
      'payment': 'Información de pago',
      'add': 'Añadir Producto',
      'edit': 'Editar producto',
      'info': 'INFORMACIÓN DEL ARTÍCULO',
      'title': 'TÍTULO DEL ARTÍCULO',
      'enterTitle': 'Ingrese el nombre del artículo',
      'itemCategory': 'CATEGORÍA DE ARTÍCULO',
      'selectCategory': 'Seleccionar categoría de artículo',
      'price': 'PRECIO DEL ARTICULO',
      'enterPrice': 'Ingrese precio',
      'quantity': 'CANTIDAD',
      'enterQuantity': 'Introducir cantidad',
      'addMore': '+AGREGAR MÁS OPCIONES',
      'image': 'Imagen del artículo',
      'newOrder': 'NUEVOS PEDIDOS',
      'pastOrder': 'pedidos anteriores',
      'vegetables': 'VEGETALES',
      'fruits': 'FRUTAS',
      'herbs': 'HIERBAS',
      'dairy': 'LECHERÍA',
      'items': 'Artículos',
      'heyThere': '¿Hola? ¿Cuanto tiempo?',
      'onMyWay': 'En mi camino, señor, llegará en 10 minutos',
      'deliveryPartner': 'entrega socio',
      'orderNumber': 'Número de orden',
    };
  }

  Map<String, String> portuguese() {
    return {
      'lightMode': 'Modo de luz',
      'lightText': 'Experimente um modo de luz emocionante',
      'accepted': 'aceitaram',
      'submit': 'Enviar',
      'outStock': 'Fora de estoque',
      'setLocation': 'Definir local de entrega',
      'enterLocation': 'Introduza a localização',
      'review': 'meus comentários',
      'hey':
          'Hey Samantha, \n\nVocê está quase dentro. \nFornecer o seu número de \ntelefone para verificação.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'sabor dos alimentos incrível, assim como serviço de entrega rápida. Realmente aprecio a embalagem ea qualidade dos alimentos entregues. Vá em frente !!',
      'content2':
          'serviço de entrega rápida e realmente um bom sabor dos alimentos. Realmente aprecio a embalagem ea qualidade dos alimentos entregues. Devem solicitar Chicken Curry.',
      'language': 'Selecione o idioma',
      'display': 'Modo de seleção',
      'darkMode': 'Modo escuro',
      'darkText': 'Experimente um modo escuro emocionante',
      'settings': 'Configurações',
      'or': 'Ou',
      'continueWith': 'Continue com',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'maçã',
      'invalidNumber': 'Número inválido',
      'networkError': 'Erro de rede',
      'bodyText1': 'Entregando quase',
      'bodyText2': 'Tudo.',
      'mobileText': 'Digite o número do celular',
      'continueText': 'Continuar',
      'register': 'Registro',
      'invalidName': 'Nome inválido',
      'invalidEmail': 'E-mail inválido',
      'invalidNameAndEmail': 'Nome e email inválidos',
      'fullName': 'Nome da loja',
      'emailAddress': 'Endereço de e-mail',
      'mobileNumber': 'Número de celular',
      'verificationText':
          'Enviaremos o código de verificação acima do número especificado.',
      'verification': 'Verificação',
      'checkNetwork': 'Verifique sua rede ou número de telefone digitado',
      'invalidOTP': 'OTP inválido',
      'enterVerification':
          'Digite o código de verificação que enviamos em determinado número.',
      'verificationCode': 'DIGITE O CÓDIGO DE VERIFICAÇÃO',
      'resend': 'Reenviar',
      'offlineText': 'Você está offline',
      'onlineText': 'Você está online',
      'goOnline': 'FIQUE ONLINE',
      'goOffline': 'FIQUE OFFLINE',
      'orders': 'Encomendas',
      'itemSold': 'Itens vendidos',
      'earnings': 'Ganhos',
      'location': 'Permissão de local negada! \ Conceda o local ao aplicativo.',
      'grant': 'Conceder',
      'homeText': 'Casa',
      'account': 'Minha conta',
      'orderText': 'minhas ordens',
      'insight': 'Discernimento',
      'wallet': 'Carteira',
      'tnc': 'termos e Condições',
      'support': 'Apoio, suporte',
      'aboutUs': 'Sobre nós',
      'logout': 'Sair',
      'login': 'Conecte-se',
      'loggingOut': 'Sair',
      'areYouSure': 'Você tem certeza?',
      'yes': 'sim',
      'no': 'Não',
      'sendToBank': 'Enviar para o banco',
      'availableBalance': 'Saldo disponível',
      'bankInfo': 'Informações bancárias',
      'accountHolderName': 'nome do titular da conta',
      'bankName': 'Nome do banco',
      'branchCode': 'Código da Agência',
      'accountNumber': 'Número da conta',
      'enterAmountToTransfer': 'Insira o valor a transferir',
      'aboutDelivoo': 'Sobre o Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'Nossa visão',
      'companyPolicy': 'Política da Empresa',
      'termsOfUse': 'Termos de uso',
      'message': 'Sua mensagem',
      'enterMessage': 'Digite sua mensagem',
      'orWrite': 'Ou escreva-nos as suas perguntas',
      'yourWords': 'Suas palavras significam muito para nós.',
      'online': 'Conectados',
      'recent': 'Recente',
      'vegetable': 'Legumes e Frutas',
      'today': 'HOJE',
      'viewAll': 'Ver todas as transações',
      'editProfile': 'Editar Perfil',
      'featureImage': 'Imagem do Recurso',
      'uploadPhoto': 'Carregar foto',
      'profileInfo': 'Informações da loja',
      'gender': 'Gênero',
      'updateInfo': 'Informação de atualização',
      'instruction': 'Mantenha os tomates em um saco separado, por favor.',
      'cod': 'Dinheiro na entrega',
      'viewOrderInfo': 'Exibir informações do pedido',
      'store': 'Vegetal de folha de prata',
      'ready': 'Pronto para entregar',
      'storeText': 'Mercado da União',
      'storeProfile': 'Perfil da loja',
      'tomato': 'Tomates vermelhos frescos',
      'onion': 'Cebolas vermelhas frescas',
      'fingers': 'Senhora fresca Dedos',
      'top': 'TOP 5 ITENS DE VENDA',
      'total': 'Total de 112 itens vendidos',
      'sales': 'Vendas',
      'category': 'Categoria',
      'address': 'Endereço',
      'storeAddress': 'Endereço da loja',
      'storeTimings': 'Horários da loja',
      'openingTime': 'Tempo de abertura',
      'closingTime': 'Horário de encerramento',
      'product': 'Meus produtos',
      'stock': 'Em estoque',
      'pending': 'Pendente',
      'item': 'ITENS)',
      'sub': 'Subtotal',
      'service': 'Taxa de serviço',
      'payment': 'Informação de pagamento',
      'add': 'Adicionar produto',
      'edit': 'Editar produto',
      'info': 'INFORMAÇÕES SOBRE O ITEM',
      'title': 'TÍTULO DO ITEM',
      'enterTitle': 'CATEGORIA DO ITEM',
      'itemCategory': 'CATEGORIA DO ITEM',
      'selectCategory': 'Selecionar categoria de item',
      'price': 'PREÇO DO ITEM',
      'enterPrice': 'Digite o preço',
      'quantity': 'QUANTIDADE',
      'enterQuantity': 'Digite a quantidade',
      'addMore': '+ ADICIONAR MAIS OPÇÕES',
      'image': 'Imagem do item',
      'newOrder': 'NOVAS ORDENS',
      'pastOrder': 'ORDENS DO PASSADO',
      'vegetables': 'LEGUMES',
      'fruits': 'FRUTOS',
      'herbs': 'ERVAS',
      'dairy': 'LATICÍNIOS',
      'items': 'Itens',
      'heyThere': 'Olá? Quanto tempo?',
      'onMyWay': 'No meu caminho de senhor, vai chegar em 10 minutos',
      'deliveryPartner': 'Delivery Partner',
      'orderNumber': 'Número do pedido',
    };
  }

  Map<String, String> indonesian() {
    return {
      'lightMode': 'Mode Cahaya',
      'lightText': 'Rasakan mode cahaya yang menarik',
      'accepted': 'diterima',
      'submit': 'Kirimkan',
      'outStock': 'Kehabisan persediaan',
      'setLocation': 'Set lokasi pengiriman',
      'enterLocation': 'Masukkan lokasi',
      'review': 'Ulasan saya',
      'hey':
          'Hey Samantha,\n\n Anda hampir di.\n Memberikan nomor telepon \nAnda untuk verifikasi.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'Mengagumkan rasa makanan serta layanan pengiriman cepat. Benar-benar menghargai kemasan dan kualitas makanan yang diantarkan. Pergi untuk itu !!',
      'content2':
          'layanan pengiriman cepat & rasa benar-benar baik makanan. Benar-benar menghargai kemasan dan kualitas makanan yang diantarkan. Harus memesan kari ayam.',
      'language': 'Pilih bahasa',
      'display': 'Pilih Mode',
      'darkMode': 'gelap Modus',
      'darkText': 'Mengalami mode gelap menarik',
      'settings': 'pengaturan',
      'or': 'Atau',
      'continueWith': 'Berlanjut dengan',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'apel',
      'invalidNumber': 'Nomor Tidak Valid',
      'networkError': 'Kesalahan Jaringan',
      'bodyText1': 'Memberikan hampir',
      'bodyText2': 'Segala sesuatu.',
      'mobileText': 'Masukkan nomor ponsel',
      'continueText': 'Terus',
      'register': 'Daftar',
      'invalidName': 'Salah nama',
      'invalidEmail': 'Email tidak valid',
      'invalidNameAndEmail': 'Nama dan Email Tidak Valid',
      'fullName': 'Nama Toko',
      'emailAddress': 'Alamat email',
      'mobileNumber': 'Nomor handphone',
      'verificationText':
          'Kami akan mengirimkan kode verifikasi pada nomor yang diberikan di atas.',
      'verification': 'Verifikasi',
      'checkNetwork':
          'Periksa jaringan atau nomor telepon Anda yang dimasukkan',
      'invalidOTP': 'OTP tidak valid',
      'enterVerification':
          'Masukkan kode verifikasi yang kami kirim pada nomor yang diberikan.',
      'verificationCode': 'MASUKKAN KODE VERIFIKASI',
      'resend': 'Kirim ulang',
      'offlineText': 'Anda sedang offline',
      'onlineText': 'Anda sedang online',
      'goOnline': 'ONLINE',
      'goOffline': 'GO OFFLINE',
      'orders': 'Pesanan',
      'itemSold': 'Barang Terjual',
      'earnings': 'Pendapatan',
      'location': 'Izin lokasi ditolak! \ Berikan lokasi ke aplikasi.',
      'grant': 'Hibah',
      'homeText': 'Rumah',
      'account': 'Akun saya',
      'orderText': 'pesananku',
      'insight': 'Wawasan',
      'wallet': 'Dompet',
      'tnc': 'Syarat & Ketentuan',
      'support': 'Dukung',
      'aboutUs': 'Tentang kami',
      'logout': 'Keluar',
      'login': 'Gabung',
      'loggingOut': 'Keluar',
      'areYouSure': 'Apakah kamu yakin',
      'yes': 'Iya',
      'no': 'Tidak',
      'sendToBank': 'Kirim ke Bankk',
      'availableBalance': 'Saldo Tersedia',
      'bankInfo': 'Info Bank',
      'accountHolderName': 'nama pemilik akun',
      'bankName': 'Nama Bank',
      'branchCode': 'Kode cabang',
      'accountNumber': 'Nomor akun',
      'enterAmountToTransfer': 'Masukkan jumlah yang akan ditransfer',
      'aboutDelivoo': 'Tentang Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'Visi Kami',
      'companyPolicy': 'Kebijakan perusahaan',
      'termsOfUse': 'Syarat Penggunaan',
      'message': 'Pesan Anda',
      'enterMessage': 'Ketik pesan anda',
      'orWrite': 'Atau Tulis kami pertanyaan Anda',
      'yourWords': 'Kata-kata Anda sangat berarti bagi kami.',
      'online': 'On line',
      'recent': 'Baru',
      'vegetable': 'Sayuran & Buah',
      'today': 'HARI INI',
      'viewAll': 'Lihat semua Transaksi',
      'editProfile': 'Lihat semua Transaksi',
      'featureImage': 'Gambar Unggulan',
      'uploadPhoto': 'Mengunggah foto',
      'profileInfo': 'Info Toko',
      'gender': 'Jenis kelamin',
      'updateInfo': 'Informasi terbaru',
      'instruction': 'Tolong simpan tomat dalam kantong terpisah.',
      'cod': 'Bayar di tempat',
      'viewOrderInfo': 'Lihat Info Pemesanan',
      'store': 'Sayuran Daun Perak',
      'ready': 'Siap Kirim',
      'storeText': 'Pasar Serikat',
      'storeProfile': 'Simpan Profil',
      'tomato': 'Tomat Merah Segar',
      'onion': 'Bawang Merah Segar',
      'fingers': 'Jari Wanita Segar',
      'top': '5 item penjualan top',
      'total': 'Total penjualan 112 item',
      'sales': 'Penjualan',
      'category': 'Kategori',
      'address': 'Alamat',
      'storeAddress': 'Alamat Toko',
      'storeTimings': 'Pengaturan Waktu Toko',
      'openingTime': 'Waktu pembukaan',
      'closingTime': 'Waktu tutup',
      'product': 'Produk saya',
      'stock': 'Persediaan',
      'pending': 'Tertunda',
      'item': 'ITEM(S)',
      'sub': 'Sub Total',
      'service': 'Biaya jasa',
      'payment': 'Informasi pembayaran',
      'add': 'Tambahkan Produk',
      'edit': 'Edit Produk',
      'info': 'INFO ITEM',
      'title': 'NAMA BARANG',
      'enterTitle': 'Masukkan Nama Item',
      'itemCategory': 'KATEGORI BARANG',
      'selectCategory': 'Pilih Kategori Barang',
      'price': 'HARGA BARANG',
      'enterPrice': 'Masukkan Harga',
      'quantity': 'KUANTITAS',
      'enterQuantity': 'Masukkan Kuantitas',
      'addMore': '+Tambahkan lebih banyak pilihan',
      'image': 'Gambar Barang',
      'newOrder': 'PESANAN BARU',
      'pastOrder': 'PESANAN PAST',
      'vegetables': 'SAYURAN',
      'fruits': 'BUAH-BUAHAN',
      'herbs': 'REMPAH',
      'dairy': 'DAIRY',
      'items': 'item',
      'heyThere': 'Hey ada? Berapa lama?',
      'onMyWay': 'Dalam perjalanan Pak saya, akan mencapai dalam 10 menit',
      'deliveryPartner': 'pengiriman Partner',
      'orderNumber': 'Jumlah order',
    };
  }

  Map<String, String> french() {
    return {
      'lightMode': 'Mode lumière',
      'lightText': 'Découvrez un mode d\'éclairage passionnant',
      'accepted': 'accepté',
      'submit': 'Soumettre',
      'outStock': 'En rupture de stock',
      'setLocation': 'Définir l\'emplacement de livraison',
      'enterLocation': 'Entrez l\'emplacement',
      'review': 'Mes critiques',
      'hey':
          'Hey Samantha,\n\n vous êtes presque. \nIndiquez votre numéro de\n téléphone pour vérification.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'le goût des aliments super ainsi que le service de livraison rapide. Vraiment apprécier l\'emballage et la qualité des aliments livrés. Fonce !!',
      'content2':
          'service de livraison rapide et vraiment bon goût des aliments. Vraiment apprécier l\'emballage et la qualité des aliments livrés. Doit commander poulet au curry.',
      'language': 'Choisir la langue',
      'display': 'Sélectionnez le mode',
      'darkMode': 'dark mode',
      'darkText': 'Découvrez un mode sombre passionnant',
      'settings': 'Paramètres',
      'or': 'Ou',
      'continueWith': 'Continue avec',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'Pomme',
      'invalidNumber': 'Numéro invalide',
      'networkError': 'Erreur réseau',
      'bodyText1': 'Livrer presque',
      'bodyText2': 'Tout.',
      'mobileText': 'Entrez le numéro de mobile',
      'continueText': 'Continuer',
      'register': 'S\'inscrire',
      'invalidName': 'Nom incorrect',
      'invalidEmail': 'Email invalide',
      'invalidNameAndEmail': 'Nom et adresse e-mail non valides',
      'fullName': 'Nom du magasin',
      'emailAddress': 'Adresse électronique',
      'mobileNumber': 'Numéro de portable',
      'verificationText':
          'Nous enverrons le code de vérification sur le numéro ci-dessus.',
      'verification': 'Vérification',
      'checkNetwork': 'Vérifiez votre réseau ou le numéro de téléphone saisi',
      'invalidOTP': 'OTP non valide',
      'enterVerification':
          'Entrez le code de vérification que nous avons envoyé sur un numéro donné.',
      'verificationCode': 'ENTREZ LE CODE DE VÉRIFICATION',
      'resend': 'Renvoyer',
      'offlineText': 'Tu es hors ligne',
      'onlineText': 'Tu es en ligne',
      'goOnline': 'ALLER EN LIGNE',
      'goOffline': 'SE DÉCONNECTER',
      'orders': 'Ordres',
      'itemSold': 'Objets vendus',
      'earnings': 'Gains',
      'location':
          'Autorisation de localisation refusée! \ Accordez la localisation à l\'application.',
      'grant': 'Subvention',
      'homeText': 'Accueil',
      'account': 'Mon compte',
      'orderText': 'Mes commandes',
      'insight': 'Perspicacité',
      'wallet': 'Portefeuille',
      'tnc': 'termes et conditions',
      'support': 'Soutien',
      'aboutUs': 'À propos de nous',
      'logout': 'Se déconnecter',
      'login': 'S\'identifier',
      'loggingOut': 'Déconnecter',
      'areYouSure': 'Êtes-vous sûr?',
      'yes': 'Oui',
      'no': 'Non',
      'sendToBank': 'Envoyer à la banque',
      'availableBalance': 'Solde disponible',
      'bankInfo': 'Informations bancaires',
      'accountHolderName': 'Nom du titulaire du compte',
      'bankName': 'Nom de banque',
      'branchCode': 'Code de la succursale',
      'accountNumber': 'Numéro de compte',
      'enterAmountToTransfer': 'Entrez le montant à transférer',
      'aboutDelivoo': 'À propos de Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'Notre vision',
      'companyPolicy': 'Politique d\'entreprise',
      'termsOfUse': 'Conditions d\'utilisation',
      'message': 'Votre message',
      'enterMessage': 'Tapez votre message',
      'orWrite': 'Ou écrivez-nous vos questions',
      'yourWords': 'Vos paroles comptent beaucoup pour nous.',
      'online': 'En ligne',
      'recent': 'Récent',
      'vegetable': 'Légumes et fruits',
      'today': 'AUJOURD\'HUI',
      'viewAll': 'Voir toutes les transactions',
      'editProfile': 'Editer le profil',
      'featureImage': 'Image caractéristique',
      'uploadPhoto': 'Envoyer la photo',
      'profileInfo': 'Informations sur le magasin',
      'gender': 'Le sexe',
      'updateInfo': 'Information sur la mise à jour',
      'instruction': 'Gardez les tomates dans un sac séparé s\'il vous plaît.',
      'cod': 'Paiement à la livraison',
      'viewOrderInfo': 'Afficher les informations de commande',
      'store': 'Légume feuille d\'argent',
      'ready': 'Prêt à livrer',
      'storeText': 'Marché de l\'Union',
      'storeProfile': '\nProfil du magasin',
      'tomato': 'Tomates rouges fraîches',
      'onion': 'Oignons rouges frais',
      'fingers': 'Doigts de dame frais',
      'top': 'TOP 5 DES ARTICLES DE VENTE',
      'total': 'Total des ventes de 112 articles',
      'sales': 'Ventes',
      'category': 'Catégorie',
      'address': 'Adresse',
      'storeAddress': 'Adresse du magasin',
      'storeTimings': 'Horaires du magasin',
      'openingTime': 'Horaire d\'ouverture',
      'closingTime': 'Heure de fermeture',
      'product': 'Mes produits',
      'stock': 'En stock',
      'pending': 'En attente',
      'item': 'ARTICLES)',
      'sub': 'Sous-total',
      'service': 'Frais de service',
      'payment': 'Information de paiement',
      'add': 'Ajouter un produit',
      'edit': 'Modifier le produit',
      'info': 'INFORMATIONS SUR L\'ARTICLE',
      'title': 'TITRE DE L\'ARTICLE',
      'enterTitle': 'Entrez le nom de l\'article',
      'itemCategory': 'CATÉGORIE D\'ARTICLES',
      'selectCategory': 'Sélectionnez la catégorie d\'article',
      'price': 'PRIX DE L\'ARTICLE',
      'enterPrice': 'Entrez le prix',
      'quantity': 'QUANTITÉ',
      'enterQuantity': 'Entrez la quantité',
      'addMore': '+ AJOUTER PLUS D\'OPTIONS',
      'image': 'Image de l\'article',
      'newOrder': 'NOUVELLES COMMANDES',
      'pastOrder': 'Historique de vos commandes',
      'vegetables': 'DES LÉGUMES',
      'fruits': 'DES FRUITS',
      'herbs': 'HERBES',
      'dairy': 'LAITIER',
      'items': 'Articles',
      'heyThere': 'Héy? Combien de temps?',
      'onMyWay': 'Sur mon chemin monsieur, atteindra en 10 minutes',
      'deliveryPartner': 'Partenaire de livraison',
      'orderNumber': 'Numéro de commande',
    };
  }

  Map<String, String> arabic() {
    return {
      'lightMode': 'وضع الضوء',
      'lightText': 'جرب وضع الإضاءة المثير',
      'accepted': 'قبلت',
      'submit': 'إرسال',
      'outStock': 'إنتهى من المخزن',
      'setLocation': 'مجموعة موقع التسليم',
      'enterLocation': 'إدخال الدولة',
      'review': 'بلدي التعليقات',
      'hey':
          'يا سامانثا،\n\n أنت تقريبا في.\n توفير رقم الهاتف\n الخاص بك للتحقق منها.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'طعم الطعام كان رائعا، وكذلك خدمة التوصيل السريع. نقدر حقا التعبئة ونوعية الطعام المقدمة. أذهب خلفها !!',
      'content2':
          'خدمة توصيل سريعة وطعم جيد حقا من المواد الغذائية. نقدر حقا التعبئة ونوعية الطعام المقدمة. يجب أن تأمر كاري الدجاج.',
      'language': 'اختار اللغة',
      'display': 'حدد الوضع',
      'darkMode': 'الوضع الظلام',
      'darkText': 'تجربة وضع الظلام مثيرة',
      'settings': 'الإعدادات',
      'or': 'أو',
      'continueWith': 'تواصل مع',
      'facebook': 'موقع التواصل الاجتماعي الفيسبوك',
      'google': 'جوجل',
      'apple': 'تفاحة',
      'invalidNumber': 'رقم غير صالح',
      'networkError': 'خطأ في الشبكة',
      'bodyText1': 'تسليم تقريبا',
      'bodyText2': 'كل شىء.',
      'mobileText': 'أدخل رقم الهاتف المحمول',
      'continueText': 'استمر',
      'register': 'تسجيل',
      'invalidName': 'الاسم غير صالح',
      'invalidEmail': 'بريد إلكتروني خاطئ',
      'invalidNameAndEmail': 'الاسم والبريد الإلكتروني غير صالحين',
      'fullName': 'اسم المتجر',
      'emailAddress': 'عنوان البريد الالكترونى',
      'mobileNumber': 'رقم الهاتف المحمول',
      'verificationText': 'سنرسل رمز التحقق على الرقم المذكور أعلاه.',
      'verification': 'التحقق',
      'checkNetwork': 'تحقق من إدخال الشبكة أو رقم الهاتف الخاص بك',
      'invalidOTP': 'OTP غير صالح',
      'enterVerification': 'أدخل رمز التحقق الذي أرسلناه على رقم معين.',
      'verificationCode': 'أدخل رمز التحقق',
      'resend': 'إعادة إرسال',
      'offlineText': 'أنت في وضع عدم الاتصال',
      'onlineText': 'أنت متصل بالإنترنت',
      'goOnline': 'اتصل بالانترنت',
      'goOffline': 'انتقل إلى وضع عدم الاتصال',
      'orders': 'الطلب',
      'itemSold': 'العناصر بيعت',
      'earnings': 'أرباح',
      'location': 'تم رفض إذن الموقع! \ امنح الموقع للتطبيق.',
      'grant': 'منحة',
      'homeText': 'الصفحة الرئيسية',
      'account': 'حسابي',
      'orderText': 'طلباتي',
      'insight': 'تبصر',
      'wallet': 'محفظة نقود',
      'tnc': 'البنود و الظروف',
      'support': 'الدعم',
      'aboutUs': 'معلومات عنا',
      'logout': 'تسجيل خروج',
      'login': 'تسجيل الدخول',
      'loggingOut': 'تسجيل الخروج',
      'areYouSure': 'هل أنت واثق؟',
      'yes': 'نعم',
      'no': 'لا',
      'sendToBank': 'أرسل إلى البنك',
      'availableBalance': 'الرصيد المتوفر',
      'bankInfo': 'معلومات البنك',
      'accountHolderName': 'اسم صاحب الحساب',
      'bankName': 'اسم البنك',
      'branchCode': 'رمز الفرع',
      'accountNumber': 'رقم حساب',
      'enterAmountToTransfer': 'أدخل المبلغ المطلوب تحويله',
      'aboutDelivoo': 'حول Delivoo',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravida vitae elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam.\n\nNam a arcu efficitur, ornare leo eu, euismod leo. Vestibulum porttitor varius leo, eget posuere felis congue vel. Sed sit amet erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, mauris libero pretium urna, non hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur eros pretium feugiat.\n',
      'ourVision': 'رؤيتنا',
      'companyPolicy': 'سياسة الشركة',
      'termsOfUse': 'شروط الاستخدام',
      'message': 'رسالتك',
      'enterMessage': 'اكتب رسالتك',
      'orWrite': 'أو اكتب لنا استفساراتكs',
      'yourWords': 'كلماتك تعني لنا الكثير.',
      'online': 'عبر الانترنت',
      'recent': 'الأخيرة',
      'vegetable': 'الخضار والفواكه',
      'today': 'اليوم',
      'viewAll': 'عرض جميع المعاملات',
      'editProfile': 'تعديل الملف الشخصي',
      'featureImage': 'صورة مميزة',
      'uploadPhoto': 'حمل الصورة',
      'profileInfo': 'معلومات المتجر',
      'gender': 'جنس',
      'updateInfo': 'تحديث المعلومات',
      'instruction': 'احتفظ بالطماطم في كيس منفصل من فضلك.',
      'cod': 'الدفع عند الاستلام',
      'viewOrderInfo': 'عرض معلومات الطلب',
      'store': 'ورق فضي نباتي',
      'ready': 'جاهز للتسليم',
      'storeText': 'سوق الاتحاد',
      'storeProfile': 'ملف تعريف المتجر',
      'tomato': 'طماطم حمراء طازجة',
      'onion': 'بصل أحمر طازج',
      'fingers': 'أصابع سيدة جديدة',
      'top': 'أفضل 5 بنود بيع',
      'total': 'إجمالي مبيعات 112 بندا',
      'sales': 'مبيعات',
      'category': 'الفئة',
      'address': 'عنوان',
      'storeAddress': 'عنوان المتجر',
      'storeTimings': 'توقيت المتجر',
      'openingTime': 'وقت مفتوح',
      'closingTime': 'وقت الإغلاق',
      'product': 'منتجاتي',
      'stock': 'في المخزن',
      'pending': 'قيد الانتظار',
      'item': 'العناصر)',
      'sub': 'المجموع الفرعي',
      'service': 'رسوم الخدمة',
      'payment': 'معلومات الدفع',
      'add': 'أضف منتج',
      'edit': 'تحرير المنتج',
      'info': 'معلومات البند',
      'title': 'عنوان البند',
      'enterTitle': 'أدخل اسم العنصر',
      'itemCategory': 'العنصر فئة',
      'selectCategory': 'حدد فئة العنصر',
      'price': 'سعر البند',
      'enterPrice': 'أدخل السعر',
      'quantity': 'كمية',
      'enterQuantity': 'أدخل الكمية',
      'addMore': '+ أضف المزيد من الخيارات',
      'image': 'صورة البند',
      'newOrder': 'طلبات جديدة',
      'pastOrder': 'أمر الماضيه',
      'vegetables': 'خضروات',
      'fruits': 'الفاكهة',
      'herbs': 'أعشاب',
      'dairy': 'منتجات الألبان',
      'items': 'العناصر',
      'heyThere': 'مرحبا؟ كم من الوقت؟',
      'onMyWay': 'في طريقي يا سيدي، هل تصل في 10 دقائق',
      'deliveryPartner': 'الشريك تسليم',
      'orderNumber': 'رقم الأمر',
    };
  }

  Map<String, String> italian() {
    return {
      'lightMode': 'Modalità Luce',
      'lightText': 'Provate un modo chiaro emozionante',
      'accepted': 'Accettato',
      'submit': 'Invia',
      'outStock': 'Esaurito',
      'setLocation': 'Imposta località di consegna',
      'enterLocation': 'Inserisci posizione',
      'review': 'Le mie recensioni',
      'hey':
          'Ehi Samantha, \n\nYou\'re quasi. \nInserisci il tuo numero di telefono \nfor verifica.',
      'name1': 'George legno',
      'name2': 'Emili Johnson',
      'content1':
          'Impressionante gusto degli alimenti, nonché servizio di consegna rapida. Davvero apprezzare l\'imballaggio e la qualità del cibo consegnato. Fallo !!',
      'content2':
          'servizio di consegna rapida e davvero buon gusto del cibo. Davvero apprezzare l\'imballaggio e la qualità del cibo consegnato. Deve ordinare Chicken Curry.',
      'language': 'Seleziona la lingua',
      'display': 'Select Mode',
      'darkMode': 'Modalità scura',
      'darkText': 'Provate una modalità scuro emozionante',
      'settings': 'impostazioni',
      'or': 'O',
      'continueWith': 'Continua con',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'Mela',
      'invalidNumber': 'Numero non valido',
      'networkError': 'Errore di rete',
      'bodyText1': 'Fornire quasi',
      'bodyText2': 'Qualunque cosa.',
      'mobileText': 'Inserire il numero di cellulare',
      'continueText': 'Continua',
      'register': 'Registrati',
      'invalidName': 'Nome non valido',
      'invalidEmail': 'E-mail non valido',
      'invalidNameAndEmail': 'Nome e-mail non valido',
      'fullName': 'Nome del negozio',
      'emailAddress': 'Indirizzo e-mail',
      'mobileNumber': 'Numero di cellulare',
      'verificationText':
          'Noi \'ll Invia codice di verifica sulla sopra dato numero.',
      'verification': 'Verifica',
      'checkNetwork': 'Controlla la tua entrò la rete o il numero di telefono',
      'invalidOTP': 'non valido OTP',
      'enterVerification':
          'Inserisci il codice di verifica che \'ve inviata il dato numero.',
      'verificationCode': 'INVIO DI VERIFICA CODE',
      'resend': 'Rispedisci',
      'offlineText': 'Si \'re Offline',
      'onlineText': 'Si \'re in linea',
      'goOnline': 'VAI ONLINE',
      'goOffline': 'VAI OFFLINE',
      'orders': 'Ordini',
      'newOrder': 'NUOVI ORDINI',
      'pastOrder': 'ordini precedenti',
      'itemSold': 'Gli oggetti venduti',
      'items': 'Elementi',
      'earnings': 'guadagni',
      'location':
          'il permesso Location negata! \ nGrant il percorso per l\'applicazione.',
      'grant': 'Concedere',
      'homeText': 'Casa',
      'account': 'Il mio conto',
      'orderText': 'i miei ordini',
      'insight': 'Intuizione',
      'wallet': 'Portafoglio',
      'tnc': 'Termini & Condizioni',
      'support': 'Supporto',
      'aboutUs': 'Chi siamo',
      'logout': 'Disconnettersi',
      'login': 'Login',
      'loggingOut': 'logout',
      'areYouSure': 'Sei sicuro?',
      'yes': 'sì',
      'no': 'No',
      'heyThere': 'Hey there? \ NCome molto tempo?',
      'onMyWay': 'Sulla mia strada ma \'am. \nwill raggiungere in 10 minuti',
      'sendToBank': 'Invia ad Bank',
      'availableBalance': 'saldo disponibile',
      'bankInfo': 'Info Bank',
      'accountHolderName': 'Nome del titolare',
      'bankName': 'Nome della banca',
      'branchCode': 'Codice della filiale',
      'accountNumber': 'Numero di conto',
      'enterAmountToTransfer': 'Inserisci importo da trasferire',
      'aboutDelivoo': 'A proposito di Delivoo',
      'aboutBody':
          '\ NLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed magna id varius. Etiam felis neque, gravida vitae Elementum non, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Fusce vitae vehicula ipsum, ut Commodo lorem. Praesent interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis eget eget diam. \ N \ nNam un arcu efficitur, ornare leo eu, leo euismod. Vestibulum porttitor varius leo, eget Inchiesta felis congue vel. SED sit amet quam erat. Mauris et ex Sapien. venenatis sed, felis sed eleifend vulputate, Mauris libero Pretium urna, non hendrerit urna quam vitae justo. Mecenate rhoncus Lectus consectetur eros Pretium feugiat. \ N',
      'ourVision': 'La nostra visione',
      'companyPolicy': 'Politica aziendale',
      'termsOfUse': 'Termini di utilizzo',
      'message': 'Il tuo messaggio',
      'enterMessage': 'Inserisci il tuo messaggio',
      'orWrite': 'O scriverci le vostre domande',
      'yourWords': 'Le tue parole significa molto per noi.',
      'online': 'in linea',
      'recent': 'Recente',
      'vegetable': 'Verdure & Frutta',
      'today': 'OGGI',
      'viewAll': 'Visualizza tutte le Operazioni',
      'editProfile': 'Modifica Profilo',
      'featureImage': 'caratteristica Immagine',
      'uploadPhoto': 'Carica una foto',
      'profileInfo': 'Info negozio',
      'gender': 'Genere',
      'updateInfo': 'Aggiornare le informazioni',
      'instruction': 'Mantenere i pomodori in borsa separata per favore.',
      'cod': 'Pagamento alla consegna',
      'viewOrderInfo': 'View Info Order',
      'store': 'Argento Foglia verdure',
      'ready': 'Pronta consegna',
      'storeText': 'Unione di mercato',
      'storeProfile': '\nStore Profilo',
      'tomato': 'Rosso fresco Pomodori',
      'onion': 'Freschi cipolle rosse',
      'fingers': 'Fresh Lady Fingers',
      'top': 'Top 5 FORTI \n',
      'total': 'Totale 112 vendite voce',
      'sales': 'I saldi',
      'vegetables': 'VERDURE',
      'fruits': 'FRUTTA',
      'herbs': 'ERBE AROMATICHE',
      'dairy': 'LATTERIA',
      'deliveryPartner': 'Delivery Partner Assegnato',
      'category': 'Categoria',
      'address': 'Indirizzo',
      'storeAddress': 'Registra indirizzo',
      'storeTimings': 'Conservare Tempi',
      'openingTime': 'Orario di apertura',
      'closingTime': 'Orario di chiusura',
      'product': 'I miei prodotti',
      'stock': 'Disponibile',
      'pending': 'in attesa di',
      'item': 'ELEMENTI)',
      'sub': 'Totale parziale',
      'service': 'Costo del servizio',
      'payment': 'Informazioni di pagamento',
      'add': 'Aggiungi prodotto',
      'edit': 'Modifica del prodotto',
      'info': 'Scheda Articolo',
      'title': 'TITOLO DELL\'OGGETTO',
      'enterTitle': 'Inserisci Nome dell\'articolo',
      'itemCategory': 'Articolo Categoria',
      'selectCategory': 'Seleziona articolo Categoria',
      'price': 'PREZZO DELL\'ARTICOLO',
      'enterPrice': 'Inserire il prezzo',
      'quantity': 'QUANTITÀ',
      'orderNumber': 'Order Num',
      'enterQuantity': 'Inserisci Quantità',
      'addMore': 'Aggiungere più OPZIONE',
      'image': 'Articolo Immagine',
    };
  }

  Map<String, String> turkish() {
    return {
      'lightMode': 'Işık Modu',
      'lightText': 'heyecan verici bir ışık modu yaşayın',
      'accepted': 'Kabul edilmiş',
      'submit': 'Sunmak',
      'outStock': 'Stoklar tükendi',
      'setLocation': 'Set teslimat yeri',
      'enterLocation': 'Konum girin',
      'review': 'Benim yorumlar',
      'hey':
          'Hey Samantha \n\neredeyse nYou\'re. \nProvide telefon numaran \nfor doğrulaması.',
      'name1': 'George Kereste',
      'name2': 'Emili Johnson',
      'content1':
          'Müthiş gıda tadı yanı sıra hızlı teslimat hizmeti. Gerçekten teslim paketleme ve gıda kalitesi için teşekkür ederiz. Göreyim seni !!',
      'content2':
          'Hızlı dağıtım hizmeti ve gıda Gerçekten iyi tat. Gerçekten teslim paketleme ve gıda kalitesi için teşekkür ederiz. Tavuk köri sipariş olmalı.',
      'language': 'Dil Seçin',
      'display': 'Mod seç',
      'darkMode': 'Koyu Modu',
      'darkText': 'heyecan verici bir karanlık modu yaşayın',
      'settings': 'Ayarlar',
      'or': 'Veya',
      'continueWith': 'İle devam et',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'elma',
      'invalidNumber': 'Geçersiz numara',
      'networkError': 'Ağ hatası',
      'bodyText1': 'teslim neredeyse',
      'bodyText2': 'Her şey.',
      'mobileText': 'cep telefonu numarasını girin',
      'continueText': 'Devam et',
      'register': 'Kayıt ol',
      'invalidName': 'Geçersiz isim',
      'invalidEmail': 'Geçersiz e-posta',
      'invalidNameAndEmail': 'Geçersiz İsim ve E-posta',
      'fullName': 'Dükkan adı',
      'emailAddress': 'E',
      'mobileNumber': 'Cep numarası',
      'verificationText':
          'Biz belirli sayıda yukarıda doğrulama kodunu göndereceğiz.',
      'verification': 'Doğrulama',
      'checkNetwork': 'Ağ veya telefon numarası Girilen çek',
      'invalidOTP': 'Geçersiz OTP',
      'enterVerification':
          ' Doğrulama kodunu biz girin verilen numarasına gönderilen ettik.',
      'verificationCode': 'DOGRULAMA KODUNU GİRİNİZ',
      'resend': 'Yeniden gönder',
      'offlineText': 'Sen re Çevrim',
      'onlineText': 'Sen Çevrimiçi re',
      'goOnline': 'ÇEVRİMİÇİ OL',
      'goOffline': 'ÇEVRİMDIŞI OL',
      'orders': 'Emirler',
      'newOrder': 'YENİ SİPARİŞLER',
      'pastOrder': 'GEÇMİŞ SİPARİŞLER',
      'itemSold': 'Satılan Öğeler',
      'items': 'Öğeler',
      'earnings': 'Kazanç',
      'location': 'Yer izni reddedildi! \nGrant uygulamasına yer.',
      'grant': 'hibe',
      'homeText': 'Ev',
      'account': 'Hesabım',
      'orderText': 'Siparişlerim',
      'insight': 'İçgörü',
      'wallet': 'Cüzdan',
      'tnc': 'şartlar ve koşullar',
      'support': 'Destek',
      'aboutUs': 'Hakkımızda',
      'logout': 'Çıkış Yap',
      'login': 'Oturum aç',
      'loggingOut': 'Çıkan açılıyor',
      'areYouSure': 'Emin misiniz?',
      'yes': 'Evet',
      'no': 'Hayır',
      'heyThere': 'Hey? \nhow kadar zaman?',
      'onMyWay': '10 dakika içinde ulaşmak nWill yolumu ma \'pm tarihinde.',
      'sendToBank': 'Bankaya gönder',
      'availableBalance': 'Kalan bakiye',
      'bankInfo': 'Banka Bilgileri',
      'accountHolderName': 'Hesap Sahibinin Adı',
      'bankName': 'Banka adı',
      'branchCode': 'Şube Kodu',
      'accountNumber': 'Hesap numarası',
      'enterAmountToTransfer': 'transfer tutarı girin',
      'aboutDelivoo': 'Delivoo Hakkında',
      'aboutBody':
          '\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar porta sagittis. Sed id varius magna. Etiam felis neque, gravidası özgeçmiş elementum olmayan, ab Ódio consequat. Mauris cursus commodo nisi sed imperdiet. Admin vitae vehicula ipsum, ut commodo lorem. Praesent interdum blandit condimentum. Curabitur vel Orcı vitae odio congue facilisis eget eget çaplı. \ N \ nNam bir Arcu efficitur, ornare Leo ab, euismod Leo. Vestibulum porttitor varius leo eget posuere felis congue vel. amet erat quam oturmak sed. Mauris et ex insan. Sed venenatis, felis sed eleifend vulputate, Mauris libero pretium urna olmayan hendrerit urna quam vitae justo. Maecenas rhoncus Lectus consectetur adresi pretium feugiat. \ N',
      'ourVision': 'Vizyonumuz',
      'companyPolicy': 'Şirket politikası',
      'termsOfUse': 'Kullanım Şartları',
      'message': 'Mesajın',
      'enterMessage': 'Mesajını yaz',
      'orWrite': 'Ya bize sorguları yazın',
      'yourWords': 'Sözlerin bizim için çok önemli.',
      'online': 'İnternet üzerinden',
      'recent': 'Son',
      'vegetable': 'Sebze ve Meyveler',
      'today': 'BUGÜN',
      'viewAll': 'Tüm İşlemleri Görüntüleme',
      'editProfile': 'Profili Düzenle',
      'featureImage': 'Özelliği Görüntü',
      'uploadPhoto': 'Fotoğraf yükle',
      'profileInfo': 'Mağaza Bilgisi',
      'gender': 'Cinsiyet',
      'updateInfo': 'Güncelleme bilgisi',
      'instruction': 'Ayrı çantada domates lütfen.',
      'cod': 'Kapıda ödeme',
      'viewOrderInfo': 'Görünüm Sipariş Bilgisi',
      'store': 'Silver Leaf Sebzeler',
      'ready': 'Sunun hazır',
      'storeText': 'Birlik Pazar',
      'storeProfile': '\ NStore Profili',
      'tomato': 'Taze Kırmızı Domates',
      'onion': 'Taze Kırmızı Soğan',
      'fingers': 'Taze Lady Fingers',
      'top': 'TOP 5 SATIŞ EŞYALAR \ N',
      'total': 'Toplam 112 madde satış',
      'sales': 'Satış',
      'vegetables': 'SEBZELER',
      'fruits': 'MEYVE',
      'herbs': 'OTLAR',
      'dairy': 'MANDIRA',
      'deliveryPartner': 'Teslim Ortağı Atanan',
      'category': 'Kategori',
      'address': 'Adres',
      'storeAddress': 'Mağaza Adresi',
      'storeTimings': 'Mağaza Zamanlamalarını',
      'openingTime': 'Açılış zamanı',
      'closingTime': 'Kapanış saati',
      'product': 'Benim Ürünleri',
      'stock': 'Stokta var',
      'pending': 'Bekliyor',
      'item': 'Ürün (ler)',
      'sub': 'Ara toplam',
      'service': 'Servis ücreti',
      'payment': 'Ödeme bilgisi',
      'add': 'ürün ekle',
      'edit': 'Düzenleme Ürün',
      'info': 'MADDE BİLGİLERİ',
      'title': 'ÜRÜN BAŞLIĞI',
      'enterTitle': 'Ürün Adı girin',
      'itemCategory': 'ÖĞE KATEGORİSİ',
      'selectCategory': 'Öğe Seç Kategori',
      'price': 'ÜRÜN FİYATI',
      'enterPrice': 'Fiyatı girin',
      'quantity': 'MİKTARI',
      'orderNumber': 'Sipariş Num',
      'enterQuantity': 'Miktarı Girme',
      'addMore': 'DAHA OPTION ADD',
      'image': 'öğe Görüntü',
    };
  }

  Map<String, String> swahili() {
    return {
      'lightMode': 'Mwanga Mode',
      'lightText': 'Uzoefu kusisimua mode mwanga',
      'accepted': 'zilizokubaliwa',
      'submit': 'wasilisha',
      'outStock': 'Nje ya hisa',
      'setLocation': 'Kuweka utoaji eneo',
      'enterLocation': 'Weka sehemu',
      'review': 'Ukaguzi wangu',
      'hey':
          'Hey Samantha, \n\nYou\'re karibu katika.\nWeka namba yako ya simu \nfor ukaguzi.',
      'name1': 'George Timber',
      'name2': 'Emili Johnson',
      'content1':
          'Awesome chakula ladha na pia kutoa huduma ya haraka. Kweli kufahamu kufunga na ubora wa chakula kujifungua. Kwenda kwa hilo !!',
      'content2':
          'Quick utoaji wa huduma na ladha Kweli nzuri ya chakula. Kweli kufahamu kufunga na ubora wa chakula kujifungua. Lazima ili Kuku Curry.',
      'language': 'Chagua lugha',
      'display': 'Chagua Mode',
      'darkMode': 'Mode Dark',
      'darkText': 'Uzoefu kusisimua mode giza',
      'settings': 'mipangilio',
      'or': 'au',
      'continueWith': 'kuendelea Pamoja',
      'facebook': 'Facebook',
      'google': 'Google',
      'apple': 'Apple',
      'invalidNumber': 'Nambari batili',
      'networkError': 'Tatizo la mtandao',
      'bodyText1': 'kutoa karibu',
      'bodyText2': 'Kila kitu.',
      'mobileText': 'Ingiza namba ya simu',
      'continueText': 'kuendelea',
      'register': 'Daftari',
      'invalidName': 'Jina batili',
      'invalidEmail': 'Barua pepe batili',
      'invalidNameAndEmail': 'Jina Batili na Barua pepe',
      'fullName': 'Hifadhi Jina',
      'emailAddress': 'Barua pepe',
      'mobileNumber': 'Namba ya simu ya mkononi',
      'verificationText':
          'Sisi \'ll kutuma nambari ya kuthibitisha kwenye juu namba fulani.',
      'verification': 'Uhakiki',
      'checkNetwork': 'Angalia mtandao au namba ya simu yako iliingia',
      'invalidOTP': 'OTP batili',
      'enterVerification':
          'Weka ya kuthibitisha sisi \'ve alimtuma na idadi fulani.',
      'verificationCode': 'ENTER ya kuthibitisha',
      'resend': 'Tuma tena',
      'offlineText': 'You \'re Offline',
      'onlineText': 'You \'re Online',
      'goOnline': 'GO ONLINE',
      'goOffline': 'nje ya mtandao',
      'orders': 'maagizo',
      'newOrder': 'Daraja NEW',
      'pastOrder': 'Daraja ZAMANI',
      'itemSold': 'vitu Kuuzwa',
      'items': 'vitu',
      'earnings': 'mapato',
      'location': 'Location hakuna idhini! \ NGrant eneo kwa programu.',
      'grant': 'Grant',
      'homeText': 'Home',
      'account': 'Akaunti yangu',
      'orderText': 'Oda zangu',
      'insight': 'Insight',
      'wallet': 'mkoba',
      'tnc': 'Sheria na Masharti',
      'support': 'Support',
      'aboutUs': 'Kuhusu sisi',
      'logout': 'Toka',
      'login': 'Ingia',
      'loggingOut': 'kuingia Kati',
      'areYouSure': 'Una uhakika?',
      'yes': 'Ndiyo',
      'no': 'Hapana',
      'heyThere': 'Hey huko? \nHow muda mwingi?',
      'onMyWay': 'Niko njiani ma\'am. \nWill kufikia baada ya dakika 10',
      'sendToBank': 'Tuma kwa Benki',
      'availableBalance': 'inapatikana Mizani',
      'bankInfo': 'Bank Info',
      'accountHolderName': 'Akaunti Jina Holder',
      'bankName': 'Jina la benki',
      'branchCode': 'Tawi',
      'accountNumber': 'Nambari ya akaunti',
      'enterAmountToTransfer': 'Weka kiasi uhamisho',
      'aboutDelivoo': 'kuhusu Delivoo',
      'aboutBody':
          '\ NLorem ipsum dolor kukaa amet, consectetur adipiscing Elit. Barua pulvinar porta sagittis. Sed id varius magna. Etiam felis wala, gravida vitae elementum mashirika, consequat eu odio. Mauris cursus commodo nisi sed imperdiet. Na admin vitae vehicula ipsum, ut commodo lorem. Wasiliana Nasi interdum blandit condimentum. Curabitur vel orci vitae odio congue facilisis Eget Eget diam. \ N \ nNam a arcu efficitur, pepe leo eu, euismod leo. Integrated porttitor varius leo, Eget posuere felis congue vel. SED kuchapishwa erat quam. Mauris et ex sapien. Sed venenatis, felis sed eleifend vulputate, Tracking libero mpiga urna, mashirika hendrerit urna quam vitae justo. Maecenas rhoncus lectus consectetur Eros mpiga feugiat. \ N',
      'ourVision': 'Dira yetu',
      'companyPolicy': 'Sera ya kampuni',
      'termsOfUse': 'Masharti ya matumizi',
      'message': 'Ujumbe wako',
      'enterMessage': 'Chapisha ujumbe wako',
      'orWrite': 'Au Andika sisi maswali yako',
      'yourWords': 'Maneno yako ina maana kubwa kwetu.',
      'online': 'online',
      'recent': 'Hivi karibuni',
      'vegetable': 'Vegetables & Matunda',
      'today': 'LEO',
      'viewAll': 'Tazama shughuli zote',
      'editProfile': 'Badilisha Wasifu',
      'featureImage': 'kipengele Image',
      'uploadPhoto': 'Pakia Picha',
      'profileInfo': 'Hifadhi Info',
      'gender': 'Jinsia',
      'updateInfo': 'Mwisho Info',
      'instruction': 'Weka nyanya katika mfuko tofauti tafadhali.',
      'cod': 'Fedha juu ya utoaji',
      'viewOrderInfo': 'View Order Info',
      'store': 'Silver Leaf Mboga',
      'ready': 'Tayari Kutoa',
      'storeText': 'Union Market',
      'storeProfile': '\nStore Profile',
      'tomato': 'Fresh Red Tomatoes',
      'onion': 'Fresh Red Vitunguu',
      'fingers': 'Fresh Lady Fingers',
      'top': 'TOP 5 kuuza vitu \ N',
      'total': 'Jumla 112 mauzo ya bidhaa',
      'sales': 'mauzo',
      'vegetables': 'mboga',
      'fruits': 'FRUITS',
      'herbs': 'mimea',
      'dairy': 'MAZIWA',
      'deliveryPartner': 'Utoaji wa Washirika kupeana',
      'category': 'Kundi',
      'address': 'Anuani',
      'storeAddress': 'Hifadhi ya anwani',
      'storeTimings': 'Hifadhi ya kuhesabu',
      'openingTime': 'ufunguzi wakati wa',
      'closingTime': 'kufunga wakati',
      'product': 'Bidhaa My',
      'stock': 'katika Stock',
      'pending': 'inasubiri',
      'item': 'ITEM (S)',
      'sub': 'Jumla ndogo',
      'service': 'Service Ada',
      'payment': 'malipo Info',
      'add': 'Kuongeza bidhaa',
      'edit': 'Edit Bidhaa',
      'info': 'ITEM INFO',
      'title': 'ITEM TITLE',
      'enterTitle': 'Ingiza Jina Item',
      'itemCategory': 'ITEM CATEGORY',
      'selectCategory': 'Chagua Bidhaa Jamii',
      'price': 'Bei ya bidhaa',
      'enterPrice': 'Weka Bei',
      'quantity': 'QUANTITY',
      'orderNumber': 'Order Num',
      'enterQuantity': 'Weka Kiasi',
      'addMore': 'ADD MORE OPTION',
      'image': 'item Image',
    };
  }

  Map<String, String> german() {
    return {
      "lightMode": "Lichtmodus",
      "lightText": "Erlebe einen aufregenden Lichtmodus",
      "accepted": "Akzeptiert",
      "submit": "Einreichen",
      "outStock": "Ausverkauft",
      "setLocation": "Lieferort festlegen",
      "enterLocation": "Ort eingeben",
      "review": "Meine Bewertungen",
      "hey":
          "Hey Samantha, du hast es fast geschafft. Gib deine Telefonnummer zur Bestätigung an.",
      "name1": "Georg Holz",
      "name2": "Emil Johnson",
      "content1":
          "Toller Geschmack sowie schneller Lieferservice. Schätzen Sie die Verpackung und Qualität der gelieferten Lebensmittel sehr. Tue es !!",
      "content2":
          "Schneller Lieferservice und wirklich guter Geschmack des Essens. Schätzen Sie die Verpackung und Qualität der gelieferten Lebensmittel wirklich. Muss Chicken Curry bestellen.",
      "language": "Sprache auswählen",
      "display": "Auswahlmodus",
      "darkMode": "Dunkler Modus",
      "darkText": "Erlebe einen aufregenden Dunkelmodus",
      "settings": "Einstellungen",
      "or": "Oder",
      "continueWith": "Weitermachen mit",
      "facebook": "Facebook",
      "google": "Google",
      "apple": "Apfel",
      "invalidNumber": "Ungültige Nummer",
      "networkError": "Netzwerkfehler",
      "bodyText1": "Lieferung fast",
      "bodyText2": "Alles.",
      "mobileText": "Handynummer eingeben",
      "continueText": "Fortsetzen",
      "register": "Registrieren",
      "invalidName": "Ungültiger Name",
      "invalidEmail": "Ungültige E-Mail",
      "invalidNameAndEmail": "Ungültiger Name und E-Mail",
      "fullName": "Geschäftsname",
      "emailAddress": "E-Mail-Addresse",
      "mobileNumber": "Handy Nummer",
      "verificationText":
          "Wir senden den Bestätigungscode an die oben angegebene Nummer.",
      "verification": "Überprüfung",
      "checkNetwork":
          "Überprüfen Sie Ihr Netzwerk oder Ihre eingegebene Telefonnummer",
      "invalidOTP": "Ungültiges OTP",
      "enterVerification":
          "Geben Sie den Bestätigungscode ein, den wir an die angegebene Nummer gesendet haben.",
      "verificationCode": "BESTÄTIGUNGSCODE EINGEBEN",
      "resend": "Erneut senden",
      "offlineText": "Sie sind offline",
      "onlineText": "Sie sind online",
      "goOnline": "ONLINE GEHEN",
      "goOffline": "GEHE OFFLINE",
      "orders": "Aufträge",
      "newOrder": "NEUE BESTELLUNGEN",
      "pastOrder": "VERGANGENE BESTELLUNGEN",
      "itemSold": "Artikel verkauft",
      "items": "Produkte",
      "earnings": "Verdienste",
      "location":
          "Standorterlaubnis verweigert! Gewähren Sie der App den Standort.",
      "grant": "Gewähren",
      "homeText": "Heim",
      "account": "Mein Konto",
      "orderText": "meine Bestellungen",
      "insight": "Einblick",
      "wallet": "Brieftasche",
      "tnc": "Terms & amp; Bedingungen",
      "support": "Unterstützung",
      "aboutUs": "Über uns",
      "logout": "Ausloggen",
      "login": "Anmeldung",
      "loggingOut": "Ausloggen",
      "areYouSure": "Bist du sicher?",
      "yes": "Ja",
      "no": "Nein",
      "heyThere": "Sie da? Wie viel Zeit?",
      "onMyWay": "Auf dem Weg, Ma'am. Wird in 10 Minuten ankommen",
      "sendToBank": "An Bank senden",
      "availableBalance": "Verfügbares Guthaben",
      "bankInfo": "Bankinfo",
      "accountHolderName": "Name des Kontoinhabers",
      "bankName": "Bank Name",
      "branchCode": "Branchencode",
      "accountNumber": "Kontonummer",
      "enterAmountToTransfer": "Geben Sie den zu überweisenden Betrag ein",
      "aboutDelivoo": "Über Delivoo",
      "aboutBody":
          "Der Schmerz selbst ist Liebe, das Hauptspeichersystem. Jede Couch ist ein Tor aus Pfeilen. Aber das ist sehr unterschiedlich. Auch die Katze nicht, das schwangere Lebenselement nicht, die Folgen des Fußballhasses. Mauris cursus commodo nisi sed imperdiet. Die Machbarkeit des Lebens selbst, damit der Komfort des Fahrzeugs. Es ist manchmal die aufregendste Soße. Curabitur vel orci vitae odio congue facilisis eget eget diam. Denn er wird zum Bogen, ein Löwe ziert einen Fußball, eine Löwen-Performance. Die Fähre ist der Löwe der verschiedenen Spieler, sie muss die Katze oder die Planung absetzen. Aber es war einiges zu holen. Mauris und ex sapien. Aber das Gift, die Katze, aber die Teenager, die Olympischen, die Ziele des freien Preises der Urne, nicht das Präsidium der Urne als nur das Leben. Maecenas rhoncus lectus consectetur eros pretium feugiat.",
      "ourVision": "Unsere Vision",
      "companyPolicy": "Unternehmenspolitik",
      "termsOfUse": "Nutzungsbedingungen",
      "message": "Ihre Nachricht",
      "enterMessage": "Geben Sie Ihre Nachricht ein",
      "orWrite": "Oder schreiben Sie uns Ihre Fragen",
      "yourWords": "Ihre Worte bedeuten uns sehr viel.",
      "online": "Online",
      "recent": "Jüngste",
      "vegetable": "Gemüse & Obst",
      "today": "HEUTE",
      "viewAll": "Alle Transaktionen anzeigen",
      "editProfile": "Profil bearbeiten",
      "featureImage": "Feature-Bild",
      "uploadPhoto": "Foto hochladen",
      "profileInfo": "Shop-Info",
      "gender": "Geschlecht",
      "updateInfo": "Updateinformation",
      "instruction":
          "Bewahren Sie die Tomaten bitte in einem separaten Beutel auf.",
      "cod": "Barzahlung bei Lieferung",
      "viewOrderInfo": "Bestellinformationen anzeigen",
      "store": "Silberblattgemüse",
      "ready": "Lieferbereit",
      "storeText": "Unionsmarkt",
      "storeProfile": "Profil speichern",
      "tomato": "Frische rote Tomaten",
      "onion": "Frische rote Zwiebeln",
      "fingers": "Frische Biskuitfinger",
      "top": "DIE 5 MEISTVERKAUFTEN ARTIKEL",
      "total": "Insgesamt 112 Artikelverkäufe",
      "sales": "Umsätze",
      "vegetables": "GEMÜSE",
      "fruits": "FRÜCHTE",
      "herbs": "KRÄUTER",
      "dairy": "MOLKEREI",
      "deliveryPartner": "Zugewiesener Lieferpartner",
      "category": "Kategorie",
      "address": "Die Anschrift",
      "storeAddress": "Adresse speichern",
      "storeTimings": "Timings speichern",
      "openingTime": "Öffnungszeit",
      "closingTime": "Geschäftsschluss",
      "product": "Meine Produkte",
      "stock": "Auf Lager",
      "pending": "Ausstehend",
      "item": "PRODUKTE)",
      "sub": "Zwischensumme",
      "service": "Servicegebühr",
      "payment": "Zahlungsinformationen",
      "add": "Produkt hinzufügen",
      "edit": "Produkt bearbeiten",
      "info": "ARTIKELINFO",
      "title": "ARTIKELBEZEICHNUNG",
      "enterTitle": "Geben Sie den Artikelnamen ein",
      "itemCategory": "ARTIKELKATEGORIE",
      "selectCategory": "Artikelkategorie auswählen",
      "price": "STÜCKPREIS",
      "enterPrice": "Preis eingeben",
      "quantity": "ANZAHL",
      "orderNumber": "Bestell-Nr",
      "enterQuantity": "Menge eingeben",
      "addMore": "+ WEITERE OPTIONEN HINZUFÜGEN",
      "image": "Artikelbild"
    };
  }

  Map<String, String> romania() {
    return {
      "lightMode": "Modul de lumină",
      "lightText": "Experimentați un mod de lumină incitant",
      "accepted": "Admis",
      "submit": "Trimite",
      "outStock": "Stoc epuizat",
      "setLocation": "Setați locația de livrare",
      "enterLocation": "Introduceți locația",
      "review": "Recenziile mele",
      "hey":
          "Bună Samantha, Aproape ați ajuns. Furnizați numărul de telefon pentru verificare.",
      "name1": "George Timber",
      "name2": "Emili Johnson",
      "content1":
          "Gust minunat de mâncare, precum și serviciu de livrare rapidă. Apreciez cu adevărat ambalajul și calitatea alimentelor livrate. Du-te !!",
      "content2":
          "Serviciu de livrare rapidă și gust foarte bun de mâncare. Apreciez cu adevărat ambalajul și calitatea alimentelor livrate. Trebuie să comandați Chicken Curry.",
      "language": "Selecteaza limba",
      "display": "Selectați Modul",
      "darkMode": "Modul întunecat",
      "darkText": "Experimentați un mod întunecat interesant",
      "settings": "Setări",
      "or": "Sau",
      "continueWith": "Continuă cu",
      "facebook": "Facebook",
      "google": "Google",
      "apple": "Măr",
      "invalidNumber": "Numar invalid",
      "networkError": "Eroare de rețea",
      "bodyText1": "Livrând aproape",
      "bodyText2": "Tot.",
      "mobileText": "Introduceți numărul de mobil",
      "continueText": "Continua",
      "register": "Inregistreaza-te",
      "invalidName": "Nume invalid",
      "invalidEmail": "E-mail invalid",
      "invalidNameAndEmail": "Nume și e-mail nevalide",
      "fullName": "Numele magazinului",
      "emailAddress": "Adresa de e-mail",
      "mobileNumber": "Număr de telefon mobil",
      "verificationText":
          "Vom trimite codul de verificare la numărul de mai sus.",
      "verification": "Verificare",
      "checkNetwork": "Verificați rețeaua sau numărul de telefon introdus",
      "invalidOTP": "OTP nevalid",
      "enterVerification":
          "Introdu codul de verificare pe care l-am trimis pe numărul dat.",
      "verificationCode": "INTRODUCEȚI CODUL DE VERIFICARE",
      "resend": "Retrimiteți",
      "offlineText": "Ești offline",
      "onlineText": "Ești online",
      "goOnline": "DU-TE ON-LINE",
      "goOffline": "ENTRĂ OFFLINE",
      "orders": "Comenzi",
      "newOrder": "COMENZI NOI",
      "pastOrder": "COMENZI ANTRECELE",
      "itemSold": "Articole vândute",
      "items": "Articole",
      "earnings": "Câștiguri",
      "location":
          "Permisiunea locației a fost refuzată! Acordați locația aplicației.",
      "grant": "Acorda",
      "homeText": "Acasă",
      "account": "Contul meu",
      "orderText": "Comenzile mele",
      "insight": "Insight",
      "wallet": "Portofel",
      "tnc": "termeni si conditii",
      "support": "A sustine",
      "aboutUs": "Despre noi",
      "logout": "Deconectare",
      "login": "Autentificare",
      "loggingOut": "Delogare",
      "areYouSure": "Esti sigur?",
      "yes": "da",
      "no": "Nu",
      "heyThere": "Hei acolo? Cât timp?",
      "onMyWay": "Pe drumul meu, doamnă. Voi ajunge în 10 minute",
      "sendToBank": "Trimite la bancă",
      "availableBalance": "Sold disponibil",
      "bankInfo": "Informații bancare",
      "accountHolderName": "Numele deținătorului contului",
      "bankName": "Numele băncii",
      "branchCode": "Codul filialei",
      "accountNumber": "Numar de cont",
      "enterAmountToTransfer": "Introduceți suma de transferat",
      "aboutDelivoo": "Despre Delivoo",
      "aboutBody":
          "Durerea în sine este dragostea, principalul sistem de stocare. Fiecare canapea este o poartă de săgeți. Dar asta variază foarte mult. Nici pisica nu, elementul de viață gravidă nu, consecințele urii de fotbal. Mauris cursus commodo nisi sed imperdiet. Fezabilitatea vieții în sine, astfel încât confortul vehiculului. Uneori este cel mai interesant sos. Curabitur vel orci vitae odio congue facilisis eget eget diam. Căci el devine un arc, un leu împodobește un fotbal, un leu Performanță. Feribotul este leul diverșilor jucători, trebuie să pună jos pisica sau planificarea. Dar erau multe de avut. Mauris et ex sapien. Dar veninosul, pisica, dar adolescenții Olimpic, obiectivele prețului gratuit al urnei, nu biroul urnei decât doar viață. Maecenas rhoncus lectus consectetur eros pretium feugiat.",
      "ourVision": "Viziunea noastra",
      "companyPolicy": "Politica companiei",
      "termsOfUse": "Termeni de utilizare",
      "message": "Mesajul dvs",
      "enterMessage": "Introduceți mesajul dvs",
      "orWrite": "Sau scrieți-ne întrebările dvs",
      "yourWords": "Cuvintele tale înseamnă foarte mult pentru noi.",
      "online": "Pe net",
      "recent": "Recent",
      "vegetable": "Legume și fructe",
      "today": "AZI",
      "viewAll": "Vedeți toate tranzacțiile",
      "editProfile": "Editează profilul",
      "featureImage": "Imagine caracteristică",
      "uploadPhoto": "Încarcă fotografie",
      "profileInfo": "Informații magazin",
      "gender": "Gen",
      "updateInfo": "Actualizare Info",
      "instruction": "Păstrați roșiile într-o pungă separată, vă rog.",
      "cod": "Plata la livrare",
      "viewOrderInfo": "Vezi informații despre comandă",
      "store": "Legume cu frunze de argint",
      "ready": "Gata de livrare",
      "storeText": "Piața Uniunii",
      "storeProfile": "Profilul magazinului",
      "tomato": "Roșii roșii proaspete",
      "onion": "Ceapa rosie proaspata",
      "fingers": "Fresh Lady Fingers",
      "top": "TOP 5 ARTICOLE VANZATE",
      "total": "Vânzări totale de 112 articole",
      "sales": "Vânzări",
      "vegetables": "LEGUME",
      "fruits": "FRUCTE",
      "herbs": "Ierburi",
      "dairy": "LACTAT",
      "deliveryPartner": "Partener de livrare a fost atribuit",
      "category": "Categorie",
      "address": "Abordare",
      "storeAddress": "Adresa magazinului",
      "storeTimings": "Orare magazin",
      "openingTime": "Ora de deschidere",
      "closingTime": "Oră de închidere",
      "product": "Produsele mele",
      "stock": "În stoc",
      "pending": "In asteptarea",
      "item": "ARTICOLE",
      "sub": "Subtotal",
      "service": "Taxa de serviciu",
      "payment": "Informatii plată",
      "add": "Adăugați produs",
      "edit": "Editați produsul",
      "info": "INFORMAȚII ARTICOL",
      "title": "TITLUL ARTICOLULUI",
      "enterTitle": "Introduceți numele articolului",
      "itemCategory": "CATEGORIA DE ARTICOLE",
      "selectCategory": "Selectați Categoria articolului",
      "price": "PRETUL ARTICOLULUI",
      "enterPrice": "Introduceți prețul",
      "quantity": "CANTITATE",
      "orderNumber": "Număr comandă",
      "enterQuantity": "Introduceți Cantitatea",
      "addMore": "+ ADĂUGAȚI MAI MULTE OPȚIUNI",
      "image": "Imaginea articolului"
    };
  }
}
